---
# title: ""
# author: "Christina Chen"
# date: "4/27/2021"
output: pdf_document
---

# Discussion
Through the four models, our analysis has addressed our research question of analyzing if educational or familial predictors are larger determinants of student success. We look at four measures of student outcome that span the trajectory of a student from 10th grade into adulthood: standardized test score, odds of dropping out of high school, odds of attaining a Bachelor's degree, and socioeconomic status as an adult. Then, in evaluating the sizes of predictors of each group, we look specifically at financial, external motivation, and environmental condition predictor groups.

An interesting conclusion of our analysis is the strong association between external motivation from teachers at school with all four outcomes. Therefore, when hiring teachers, schools should place an emphasis to look for teachers who have a potential to truly invest emotionally in and build relationships with their students. 

In terms of high school related outcomes, an important finding is that on the financial and condition axes, familial predictors are the larger determinants of test composite score. Although this does not allow us to conclude an insignificance of funding in schools due to the lack of data that represents funding, this aligns with Coleman's findings in his paper that showed that familial factors were indeed significant in correlation to test scores. However, when looking at another high school related outcome, the odds of dropping out, educational factors become larger determinants along all axes, especially for schools that are in a poorer area. Therefore, our analysis demonstrates the benefits of investigating student success past solely test score, since attaining a GED is an achievement in and of itself. Our conclusions support the findings in the 2015 study that showed that a 10% of an increase in spending per student lead to more completed years of education and higher wages, espeically for low socioeconomic students. More practically, our results show the need for lawmakers to prioritize investment in reducing class sizes or finding larger spaces at schools in less wealthy districts.

Past high school, we see a similar conclusion for the odds of attaining a Bachelor's degree as the conclusion from the model for test composite score. Familial predictors are the larger determinants of the odds of attaining a Bachelor's. The strong association of familial predictors is possibly due to the simple need for financial support for college, which usually comes from the student's family. For the student's SES quantile as an adult, we see similar conclusions, except educational financial predictors are leveled with familial financial predictors in the strength of association. A large component of the educational predictor is the school type. Therefore, it is possible that the communities built within private schools, which would be comprised of students from wealthier families, produce a similar bubble of financially successful students in the future. To further investigate this, predictors related to a student's friends at school could be included to look at the financial status of a student's community.

A limitation of our models is the possible violation of the independence assumptions, as mentioned previously. This could be addressed by getting access to the full dataset and using a mixed effects model using a student's school. Another limitation is that we are not directly looking at educational financial predictors, such as school funding, but rather proxies, such as the percentage of students with free lunch and the school type. Therefore, these may capture other effects that are not directly correlated with school spending. Next, a limitation is the way that familial and educational predictors were compared using the axes. These axes were created for easier comparison and analysis of association strength of the predictor groups. However, these probably are not completely separate groupings. For example, financial effects may very be well reflected in the conditions factors, as funding is related to the quality of environment. Finally, there is the limitation of the multitude of categorical variables and the need to collapse levels to increase sample size. Therefore, this resulted in a loss of data, and these categorical levels may be handled in other ways to further support our results. However, we did perform sensitivity analyses which supported our results with imputed data.

The data itself is reliable, as it comes from a reputable source and from a long term study. However, a possible source of ambiguity is the learning hindrance variables, since they are based on someone's subjective opinion on how much learning is hindered based on a specific condition. However, our use of a binary encoding for these variables may evade this issue.

An interesting route for further analysis would be to include the test composite score in the other models. This may shed some light on some sort of indirect significance of familial or educational predictors on student outcomes that come after mere test scores. Additionally, it may be helpful to compare p-values, in addition to coefficient sizes, when comparing familial and educational factors. This may lead to stronger results, which could align more with the sensitivity analysis results, as variables with extremely small p-values in the main models are probably more likely to be significant in the sensitivity analyses with non-imputed data.

Our analysis investigated multiple facets of student success, which illuminated interesting findings surrounding areas to focus on when funding schools or hiring teachers. In addition, we found areas that could warrant for further investigation, such as models with more predictors. Overall, we believe that the use of multiple measures of student outcome, instead of solely standardized test scores, bring more depth to the debate surrounding school funding.